.....................ERROR:Internal Server Error: /assessment/201530/EG500001/unitplan1/21743148/
Traceback (most recent call last):
  File "C:\Python33\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python33\lib\site-packages\django\contrib\auth\decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\python33\assessmenttoolstaging\source\rubricapp\views.py", line 123, in rubric_page
    RubricData.objects.create(assignment=classassignment, enrollment__student=student)
  File "C:\Python33\lib\site-packages\django\db\models\manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Python33\lib\site-packages\django\db\models\query.py", line 346, in create
    obj = self.model(**kwargs)
  File "C:\Python33\lib\site-packages\django\db\models\base.py", line 480, in __init__
    raise TypeError("'%s' is an invalid keyword argument for this function" % list(kwargs)[0])
TypeError: 'enrollment__student' is an invalid keyword argument for this function
E......F.................ERROR:Internal Server Error: /assessment/201530/EG500001/WritingAssignment1/21743148/
Traceback (most recent call last):
  File "C:\Python33\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python33\lib\site-packages\django\contrib\auth\decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\python33\assessmenttoolstaging\source\rubricapp\views.py", line 123, in rubric_page
    RubricData.objects.create(assignment=classassignment, enrollment__student=student)
  File "C:\Python33\lib\site-packages\django\db\models\manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Python33\lib\site-packages\django\db\models\query.py", line 346, in create
    obj = self.model(**kwargs)
  File "C:\Python33\lib\site-packages\django\db\models\base.py", line 480, in __init__
    raise TypeError("'%s' is an invalid keyword argument for this function" % list(kwargs)[0])
TypeError: 'enrollment__student' is an invalid keyword argument for this function
EERROR:Internal Server Error: /assessment/201530/EG500001/writingassignment1/21743148/
Traceback (most recent call last):
  File "C:\Python33\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python33\lib\site-packages\django\contrib\auth\decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\python33\assessmenttoolstaging\source\rubricapp\views.py", line 123, in rubric_page
    RubricData.objects.create(assignment=classassignment, enrollment__student=student)
  File "C:\Python33\lib\site-packages\django\db\models\manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Python33\lib\site-packages\django\db\models\query.py", line 346, in create
    obj = self.model(**kwargs)
  File "C:\Python33\lib\site-packages\django\db\models\base.py", line 480, in __init__
    raise TypeError("'%s' is an invalid keyword argument for this function" % list(kwargs)[0])
TypeError: 'enrollment__student' is an invalid keyword argument for this function
EERROR:Internal Server Error: /assessment/201530/EG500001/writingassignment1/21743148/
Traceback (most recent call last):
  File "C:\Python33\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python33\lib\site-packages\django\contrib\auth\decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\python33\assessmenttoolstaging\source\rubricapp\views.py", line 123, in rubric_page
    RubricData.objects.create(assignment=classassignment, enrollment__student=student)
  File "C:\Python33\lib\site-packages\django\db\models\manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Python33\lib\site-packages\django\db\models\query.py", line 346, in create
    obj = self.model(**kwargs)
  File "C:\Python33\lib\site-packages\django\db\models\base.py", line 480, in __init__
    raise TypeError("'%s' is an invalid keyword argument for this function" % list(kwargs)[0])
TypeError: 'enrollment__student' is an invalid keyword argument for this function
EERROR:Internal Server Error: /assessment/201530/EG500001/writingassignment1/21743148/
Traceback (most recent call last):
  File "C:\Python33\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python33\lib\site-packages\django\contrib\auth\decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\python33\assessmenttoolstaging\source\rubricapp\views.py", line 123, in rubric_page
    RubricData.objects.create(assignment=classassignment, enrollment__student=student)
  File "C:\Python33\lib\site-packages\django\db\models\manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Python33\lib\site-packages\django\db\models\query.py", line 346, in create
    obj = self.model(**kwargs)
  File "C:\Python33\lib\site-packages\django\db\models\base.py", line 480, in __init__
    raise TypeError("'%s' is an invalid keyword argument for this function" % list(kwargs)[0])
TypeError: 'enrollment__student' is an invalid keyword argument for this function
EERROR:Internal Server Error: /assessment/201530/EG500001/writingassignment1/21743148/
Traceback (most recent call last):
  File "C:\Python33\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python33\lib\site-packages\django\contrib\auth\decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\python33\assessmenttoolstaging\source\rubricapp\views.py", line 123, in rubric_page
    RubricData.objects.create(assignment=classassignment, enrollment__student=student)
  File "C:\Python33\lib\site-packages\django\db\models\manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Python33\lib\site-packages\django\db\models\query.py", line 346, in create
    obj = self.model(**kwargs)
  File "C:\Python33\lib\site-packages\django\db\models\base.py", line 480, in __init__
    raise TypeError("'%s' is an invalid keyword argument for this function" % list(kwargs)[0])
TypeError: 'enrollment__student' is an invalid keyword argument for this function
EERROR:Internal Server Error: /assessment/201530/EG500001/writingassignment1/21743148/
Traceback (most recent call last):
  File "C:\Python33\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python33\lib\site-packages\django\contrib\auth\decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\python33\assessmenttoolstaging\source\rubricapp\views.py", line 123, in rubric_page
    RubricData.objects.create(assignment=classassignment, enrollment__student=student)
  File "C:\Python33\lib\site-packages\django\db\models\manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Python33\lib\site-packages\django\db\models\query.py", line 346, in create
    obj = self.model(**kwargs)
  File "C:\Python33\lib\site-packages\django\db\models\base.py", line 480, in __init__
    raise TypeError("'%s' is an invalid keyword argument for this function" % list(kwargs)[0])
TypeError: 'enrollment__student' is an invalid keyword argument for this function
EERROR:Internal Server Error: /assessment/201530/EG500001/writingassignment1/21743148/
Traceback (most recent call last):
  File "C:\Python33\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python33\lib\site-packages\django\contrib\auth\decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\python33\assessmenttoolstaging\source\rubricapp\views.py", line 123, in rubric_page
    RubricData.objects.create(assignment=classassignment, enrollment__student=student)
  File "C:\Python33\lib\site-packages\django\db\models\manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Python33\lib\site-packages\django\db\models\query.py", line 346, in create
    obj = self.model(**kwargs)
  File "C:\Python33\lib\site-packages\django\db\models\base.py", line 480, in __init__
    raise TypeError("'%s' is an invalid keyword argument for this function" % list(kwargs)[0])
TypeError: 'enrollment__student' is an invalid keyword argument for this function
EERROR:Internal Server Error: /assessment/201610/EG500001/WritingAssignment4/21743444/
Traceback (most recent call last):
  File "C:\Python33\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python33\lib\site-packages\django\contrib\auth\decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\python33\assessmenttoolstaging\source\rubricapp\views.py", line 123, in rubric_page
    RubricData.objects.create(assignment=classassignment, enrollment__student=student)
  File "C:\Python33\lib\site-packages\django\db\models\manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Python33\lib\site-packages\django\db\models\query.py", line 346, in create
    obj = self.model(**kwargs)
  File "C:\Python33\lib\site-packages\django\db\models\base.py", line 480, in __init__
    raise TypeError("'%s' is an invalid keyword argument for this function" % list(kwargs)[0])
TypeError: 'enrollment__student' is an invalid keyword argument for this function
EERROR:Internal Server Error: /assessment/201530/EG500001/writingassignment1/21743148/
Traceback (most recent call last):
  File "C:\Python33\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python33\lib\site-packages\django\contrib\auth\decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\python33\assessmenttoolstaging\source\rubricapp\views.py", line 123, in rubric_page
    RubricData.objects.create(assignment=classassignment, enrollment__student=student)
  File "C:\Python33\lib\site-packages\django\db\models\manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Python33\lib\site-packages\django\db\models\query.py", line 346, in create
    obj = self.model(**kwargs)
  File "C:\Python33\lib\site-packages\django\db\models\base.py", line 480, in __init__
    raise TypeError("'%s' is an invalid keyword argument for this function" % list(kwargs)[0])
TypeError: 'enrollment__student' is an invalid keyword argument for this function
E.ERROR:Internal Server Error: /assessment/201530/EG500001/writingassignment1/21743148/
Traceback (most recent call last):
  File "C:\Python33\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python33\lib\site-packages\django\contrib\auth\decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\python33\assessmenttoolstaging\source\rubricapp\views.py", line 123, in rubric_page
    RubricData.objects.create(assignment=classassignment, enrollment__student=student)
  File "C:\Python33\lib\site-packages\django\db\models\manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Python33\lib\site-packages\django\db\models\query.py", line 346, in create
    obj = self.model(**kwargs)
  File "C:\Python33\lib\site-packages\django\db\models\base.py", line 480, in __init__
    raise TypeError("'%s' is an invalid keyword argument for this function" % list(kwargs)[0])
TypeError: 'enrollment__student' is an invalid keyword argument for this function
EERROR:Internal Server Error: /assessment/201530/EG500001/writingassignment1/21743148/
Traceback (most recent call last):
  File "C:\Python33\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python33\lib\site-packages\django\contrib\auth\decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\python33\assessmenttoolstaging\source\rubricapp\views.py", line 123, in rubric_page
    RubricData.objects.create(assignment=classassignment, enrollment__student=student)
  File "C:\Python33\lib\site-packages\django\db\models\manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Python33\lib\site-packages\django\db\models\query.py", line 346, in create
    obj = self.model(**kwargs)
  File "C:\Python33\lib\site-packages\django\db\models\base.py", line 480, in __init__
    raise TypeError("'%s' is an invalid keyword argument for this function" % list(kwargs)[0])
TypeError: 'enrollment__student' is an invalid keyword argument for this function
EERROR:Internal Server Error: /assessment/201530/EG500001/writingassignment1/21743148/
Traceback (most recent call last):
  File "C:\Python33\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python33\lib\site-packages\django\contrib\auth\decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\python33\assessmenttoolstaging\source\rubricapp\views.py", line 123, in rubric_page
    RubricData.objects.create(assignment=classassignment, enrollment__student=student)
  File "C:\Python33\lib\site-packages\django\db\models\manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Python33\lib\site-packages\django\db\models\query.py", line 346, in create
    obj = self.model(**kwargs)
  File "C:\Python33\lib\site-packages\django\db\models\base.py", line 480, in __init__
    raise TypeError("'%s' is an invalid keyword argument for this function" % list(kwargs)[0])
TypeError: 'enrollment__student' is an invalid keyword argument for this function
EERROR:Internal Server Error: /assessment/201530/EG500001/writingassignment1/21743148/
Traceback (most recent call last):
  File "C:\Python33\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python33\lib\site-packages\django\contrib\auth\decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\python33\assessmenttoolstaging\source\rubricapp\views.py", line 123, in rubric_page
    RubricData.objects.create(assignment=classassignment, enrollment__student=student)
  File "C:\Python33\lib\site-packages\django\db\models\manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Python33\lib\site-packages\django\db\models\query.py", line 346, in create
    obj = self.model(**kwargs)
  File "C:\Python33\lib\site-packages\django\db\models\base.py", line 480, in __init__
    raise TypeError("'%s' is an invalid keyword argument for this function" % list(kwargs)[0])
TypeError: 'enrollment__student' is an invalid keyword argument for this function
EERROR:Internal Server Error: /assessment/201530/EG500001/writingassignment1/21743148/
Traceback (most recent call last):
  File "C:\Python33\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python33\lib\site-packages\django\contrib\auth\decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\python33\assessmenttoolstaging\source\rubricapp\views.py", line 123, in rubric_page
    RubricData.objects.create(assignment=classassignment, enrollment__student=student)
  File "C:\Python33\lib\site-packages\django\db\models\manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Python33\lib\site-packages\django\db\models\query.py", line 346, in create
    obj = self.model(**kwargs)
  File "C:\Python33\lib\site-packages\django\db\models\base.py", line 480, in __init__
    raise TypeError("'%s' is an invalid keyword argument for this function" % list(kwargs)[0])
TypeError: 'enrollment__student' is an invalid keyword argument for this function
EERROR:Internal Server Error: /assessment/201530/EG500001/writingassignment1/21743148/
Traceback (most recent call last):
  File "C:\Python33\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python33\lib\site-packages\django\contrib\auth\decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\python33\assessmenttoolstaging\source\rubricapp\views.py", line 123, in rubric_page
    RubricData.objects.create(assignment=classassignment, enrollment__student=student)
  File "C:\Python33\lib\site-packages\django\db\models\manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Python33\lib\site-packages\django\db\models\query.py", line 346, in create
    obj = self.model(**kwargs)
  File "C:\Python33\lib\site-packages\django\db\models\base.py", line 480, in __init__
    raise TypeError("'%s' is an invalid keyword argument for this function" % list(kwargs)[0])
TypeError: 'enrollment__student' is an invalid keyword argument for this function
E.......
======================================================================
ERROR: test_student_can_have_more_than_one_assignment_in_course (rubricapp.tests.test_views.AssignmentViewTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\python33\assessmenttoolstaging\source\rubricapp\tests\test_views.py", line 393, in test_student_can_have_more_than_one_assignment_in_course
    response = self.client.post("/assessment/201530/EG500001/unitplan{}/21743148/".format(unitassignment.pk), data)
  File "C:\Python33\lib\site-packages\django\test\client.py", line 512, in post
    secure=secure, **extra)
  File "C:\Python33\lib\site-packages\django\test\client.py", line 313, in post
    secure=secure, **extra)
  File "C:\Python33\lib\site-packages\django\test\client.py", line 379, in generic
    return self.request(**r)
  File "C:\Python33\lib\site-packages\django\test\client.py", line 466, in request
    six.reraise(*exc_info)
  File "C:\Python33\lib\site-packages\django\utils\six.py", line 659, in reraise
    raise value
  File "C:\Python33\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python33\lib\site-packages\django\contrib\auth\decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\python33\assessmenttoolstaging\source\rubricapp\views.py", line 123, in rubric_page
    RubricData.objects.create(assignment=classassignment, enrollment__student=student)
  File "C:\Python33\lib\site-packages\django\db\models\manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Python33\lib\site-packages\django\db\models\query.py", line 346, in create
    obj = self.model(**kwargs)
  File "C:\Python33\lib\site-packages\django\db\models\base.py", line 480, in __init__
    raise TypeError("'%s' is an invalid keyword argument for this function" % list(kwargs)[0])
TypeError: 'enrollment__student' is an invalid keyword argument for this function

======================================================================
ERROR: test_get_request_for_student_rubric_page_returns_rubric_if_completedrubric_false (rubricapp.tests.test_views.StudentandRubricViewTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\python33\assessmenttoolstaging\source\rubricapp\tests\test_views.py", line 636, in test_get_request_for_student_rubric_page_returns_rubric_if_completedrubric_false
    response = self.client.get("/assessment/201530/EG500001/WritingAssignment1/21743148/")
  File "C:\Python33\lib\site-packages\django\test\client.py", line 500, in get
    **extra)
  File "C:\Python33\lib\site-packages\django\test\client.py", line 303, in get
    return self.generic('GET', path, secure=secure, **r)
  File "C:\Python33\lib\site-packages\django\test\client.py", line 379, in generic
    return self.request(**r)
  File "C:\Python33\lib\site-packages\django\test\client.py", line 466, in request
    six.reraise(*exc_info)
  File "C:\Python33\lib\site-packages\django\utils\six.py", line 659, in reraise
    raise value
  File "C:\Python33\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python33\lib\site-packages\django\contrib\auth\decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\python33\assessmenttoolstaging\source\rubricapp\views.py", line 123, in rubric_page
    RubricData.objects.create(assignment=classassignment, enrollment__student=student)
  File "C:\Python33\lib\site-packages\django\db\models\manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Python33\lib\site-packages\django\db\models\query.py", line 346, in create
    obj = self.model(**kwargs)
  File "C:\Python33\lib\site-packages\django\db\models\base.py", line 480, in __init__
    raise TypeError("'%s' is an invalid keyword argument for this function" % list(kwargs)[0])
TypeError: 'enrollment__student' is an invalid keyword argument for this function

======================================================================
ERROR: test_post_request_creates_new_rubric_for_the_enrollment (rubricapp.tests.test_views.StudentandRubricViewTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\python33\assessmenttoolstaging\source\rubricapp\tests\test_views.py", line 519, in test_post_request_creates_new_rubric_for_the_enrollment
    response = self.client.get("/assessment/201530/EG500001/writingassignment1/21743148/")
  File "C:\Python33\lib\site-packages\django\test\client.py", line 500, in get
    **extra)
  File "C:\Python33\lib\site-packages\django\test\client.py", line 303, in get
    return self.generic('GET', path, secure=secure, **r)
  File "C:\Python33\lib\site-packages\django\test\client.py", line 379, in generic
    return self.request(**r)
  File "C:\Python33\lib\site-packages\django\test\client.py", line 466, in request
    six.reraise(*exc_info)
  File "C:\Python33\lib\site-packages\django\utils\six.py", line 659, in reraise
    raise value
  File "C:\Python33\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python33\lib\site-packages\django\contrib\auth\decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\python33\assessmenttoolstaging\source\rubricapp\views.py", line 123, in rubric_page
    RubricData.objects.create(assignment=classassignment, enrollment__student=student)
  File "C:\Python33\lib\site-packages\django\db\models\manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Python33\lib\site-packages\django\db\models\query.py", line 346, in create
    obj = self.model(**kwargs)
  File "C:\Python33\lib\site-packages\django\db\models\base.py", line 480, in __init__
    raise TypeError("'%s' is an invalid keyword argument for this function" % list(kwargs)[0])
TypeError: 'enrollment__student' is an invalid keyword argument for this function

======================================================================
ERROR: test_post_request_does_not_create_blank_enrollment_if_empty_row (rubricapp.tests.test_views.StudentandRubricViewTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\python33\assessmenttoolstaging\source\rubricapp\tests\test_views.py", line 612, in test_post_request_does_not_create_blank_enrollment_if_empty_row
    response = self.client.get("/assessment/201530/EG500001/writingassignment1/21743148/")
  File "C:\Python33\lib\site-packages\django\test\client.py", line 500, in get
    **extra)
  File "C:\Python33\lib\site-packages\django\test\client.py", line 303, in get
    return self.generic('GET', path, secure=secure, **r)
  File "C:\Python33\lib\site-packages\django\test\client.py", line 379, in generic
    return self.request(**r)
  File "C:\Python33\lib\site-packages\django\test\client.py", line 466, in request
    six.reraise(*exc_info)
  File "C:\Python33\lib\site-packages\django\utils\six.py", line 659, in reraise
    raise value
  File "C:\Python33\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python33\lib\site-packages\django\contrib\auth\decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\python33\assessmenttoolstaging\source\rubricapp\views.py", line 123, in rubric_page
    RubricData.objects.create(assignment=classassignment, enrollment__student=student)
  File "C:\Python33\lib\site-packages\django\db\models\manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Python33\lib\site-packages\django\db\models\query.py", line 346, in create
    obj = self.model(**kwargs)
  File "C:\Python33\lib\site-packages\django\db\models\base.py", line 480, in __init__
    raise TypeError("'%s' is an invalid keyword argument for this function" % list(kwargs)[0])
TypeError: 'enrollment__student' is an invalid keyword argument for this function

======================================================================
ERROR: test_post_request_does_not_take_0_value (rubricapp.tests.test_views.StudentandRubricViewTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\python33\assessmenttoolstaging\source\rubricapp\tests\test_views.py", line 580, in test_post_request_does_not_take_0_value
    response = self.client.get("/assessment/201530/EG500001/writingassignment1/21743148/")
  File "C:\Python33\lib\site-packages\django\test\client.py", line 500, in get
    **extra)
  File "C:\Python33\lib\site-packages\django\test\client.py", line 303, in get
    return self.generic('GET', path, secure=secure, **r)
  File "C:\Python33\lib\site-packages\django\test\client.py", line 379, in generic
    return self.request(**r)
  File "C:\Python33\lib\site-packages\django\test\client.py", line 466, in request
    six.reraise(*exc_info)
  File "C:\Python33\lib\site-packages\django\utils\six.py", line 659, in reraise
    raise value
  File "C:\Python33\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python33\lib\site-packages\django\contrib\auth\decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\python33\assessmenttoolstaging\source\rubricapp\views.py", line 123, in rubric_page
    RubricData.objects.create(assignment=classassignment, enrollment__student=student)
  File "C:\Python33\lib\site-packages\django\db\models\manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Python33\lib\site-packages\django\db\models\query.py", line 346, in create
    obj = self.model(**kwargs)
  File "C:\Python33\lib\site-packages\django\db\models\base.py", line 480, in __init__
    raise TypeError("'%s' is an invalid keyword argument for this function" % list(kwargs)[0])
TypeError: 'enrollment__student' is an invalid keyword argument for this function

======================================================================
ERROR: test_post_request_updates_correct_model (rubricapp.tests.test_views.StudentandRubricViewTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\python33\assessmenttoolstaging\source\rubricapp\tests\test_views.py", line 560, in test_post_request_updates_correct_model
    response = self.client.get("/assessment/201530/EG500001/writingassignment1/21743148/")
  File "C:\Python33\lib\site-packages\django\test\client.py", line 500, in get
    **extra)
  File "C:\Python33\lib\site-packages\django\test\client.py", line 303, in get
    return self.generic('GET', path, secure=secure, **r)
  File "C:\Python33\lib\site-packages\django\test\client.py", line 379, in generic
    return self.request(**r)
  File "C:\Python33\lib\site-packages\django\test\client.py", line 466, in request
    six.reraise(*exc_info)
  File "C:\Python33\lib\site-packages\django\utils\six.py", line 659, in reraise
    raise value
  File "C:\Python33\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python33\lib\site-packages\django\contrib\auth\decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\python33\assessmenttoolstaging\source\rubricapp\views.py", line 123, in rubric_page
    RubricData.objects.create(assignment=classassignment, enrollment__student=student)
  File "C:\Python33\lib\site-packages\django\db\models\manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Python33\lib\site-packages\django\db\models\query.py", line 346, in create
    obj = self.model(**kwargs)
  File "C:\Python33\lib\site-packages\django\db\models\base.py", line 480, in __init__
    raise TypeError("'%s' is an invalid keyword argument for this function" % list(kwargs)[0])
TypeError: 'enrollment__student' is an invalid keyword argument for this function

======================================================================
ERROR: test_post_request_with_0_value_doesnt_return_null_row_values (rubricapp.tests.test_views.StudentandRubricViewTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\python33\assessmenttoolstaging\source\rubricapp\tests\test_views.py", line 596, in test_post_request_with_0_value_doesnt_return_null_row_values
    response = self.client.get("/assessment/201530/EG500001/writingassignment1/21743148/")
  File "C:\Python33\lib\site-packages\django\test\client.py", line 500, in get
    **extra)
  File "C:\Python33\lib\site-packages\django\test\client.py", line 303, in get
    return self.generic('GET', path, secure=secure, **r)
  File "C:\Python33\lib\site-packages\django\test\client.py", line 379, in generic
    return self.request(**r)
  File "C:\Python33\lib\site-packages\django\test\client.py", line 466, in request
    six.reraise(*exc_info)
  File "C:\Python33\lib\site-packages\django\utils\six.py", line 659, in reraise
    raise value
  File "C:\Python33\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python33\lib\site-packages\django\contrib\auth\decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\python33\assessmenttoolstaging\source\rubricapp\views.py", line 123, in rubric_page
    RubricData.objects.create(assignment=classassignment, enrollment__student=student)
  File "C:\Python33\lib\site-packages\django\db\models\manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Python33\lib\site-packages\django\db\models\query.py", line 346, in create
    obj = self.model(**kwargs)
  File "C:\Python33\lib\site-packages\django\db\models\base.py", line 480, in __init__
    raise TypeError("'%s' is an invalid keyword argument for this function" % list(kwargs)[0])
TypeError: 'enrollment__student' is an invalid keyword argument for this function

======================================================================
ERROR: test_rubric_for_different_semester_doesnt_show_up_wrong_semester (rubricapp.tests.test_views.StudentandRubricViewTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\python33\assessmenttoolstaging\source\rubricapp\tests\test_views.py", line 671, in test_rubric_for_different_semester_doesnt_show_up_wrong_semester
    response = self.client.get('/assessment/201530/EG500001/writingassignment1/21743148/')
  File "C:\Python33\lib\site-packages\django\test\client.py", line 500, in get
    **extra)
  File "C:\Python33\lib\site-packages\django\test\client.py", line 303, in get
    return self.generic('GET', path, secure=secure, **r)
  File "C:\Python33\lib\site-packages\django\test\client.py", line 379, in generic
    return self.request(**r)
  File "C:\Python33\lib\site-packages\django\test\client.py", line 466, in request
    six.reraise(*exc_info)
  File "C:\Python33\lib\site-packages\django\utils\six.py", line 659, in reraise
    raise value
  File "C:\Python33\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python33\lib\site-packages\django\contrib\auth\decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\python33\assessmenttoolstaging\source\rubricapp\views.py", line 123, in rubric_page
    RubricData.objects.create(assignment=classassignment, enrollment__student=student)
  File "C:\Python33\lib\site-packages\django\db\models\manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Python33\lib\site-packages\django\db\models\query.py", line 346, in create
    obj = self.model(**kwargs)
  File "C:\Python33\lib\site-packages\django\db\models\base.py", line 480, in __init__
    raise TypeError("'%s' is an invalid keyword argument for this function" % list(kwargs)[0])
TypeError: 'enrollment__student' is an invalid keyword argument for this function

======================================================================
ERROR: test_rubric_for_different_semester_doesnt_shows_up_in_correct_semester (rubricapp.tests.test_views.StudentandRubricViewTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\python33\assessmenttoolstaging\source\rubricapp\tests\test_views.py", line 654, in test_rubric_for_different_semester_doesnt_shows_up_in_correct_semester
    response = self.client.get('/assessment/201610/EG500001/WritingAssignment'+ str(edclassnewsemester.pk) +'/21743444/')
  File "C:\Python33\lib\site-packages\django\test\client.py", line 500, in get
    **extra)
  File "C:\Python33\lib\site-packages\django\test\client.py", line 303, in get
    return self.generic('GET', path, secure=secure, **r)
  File "C:\Python33\lib\site-packages\django\test\client.py", line 379, in generic
    return self.request(**r)
  File "C:\Python33\lib\site-packages\django\test\client.py", line 466, in request
    six.reraise(*exc_info)
  File "C:\Python33\lib\site-packages\django\utils\six.py", line 659, in reraise
    raise value
  File "C:\Python33\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python33\lib\site-packages\django\contrib\auth\decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\python33\assessmenttoolstaging\source\rubricapp\views.py", line 123, in rubric_page
    RubricData.objects.create(assignment=classassignment, enrollment__student=student)
  File "C:\Python33\lib\site-packages\django\db\models\manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Python33\lib\site-packages\django\db\models\query.py", line 346, in create
    obj = self.model(**kwargs)
  File "C:\Python33\lib\site-packages\django\db\models\base.py", line 480, in __init__
    raise TypeError("'%s' is an invalid keyword argument for this function" % list(kwargs)[0])
TypeError: 'enrollment__student' is an invalid keyword argument for this function

======================================================================
ERROR: test_rubric_page_can_take_post_request (rubricapp.tests.test_views.StudentandRubricViewTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\python33\assessmenttoolstaging\source\rubricapp\tests\test_views.py", line 495, in test_rubric_page_can_take_post_request
    response = self.client.get("/assessment/201530/EG500001/writingassignment1/21743148/")
  File "C:\Python33\lib\site-packages\django\test\client.py", line 500, in get
    **extra)
  File "C:\Python33\lib\site-packages\django\test\client.py", line 303, in get
    return self.generic('GET', path, secure=secure, **r)
  File "C:\Python33\lib\site-packages\django\test\client.py", line 379, in generic
    return self.request(**r)
  File "C:\Python33\lib\site-packages\django\test\client.py", line 466, in request
    six.reraise(*exc_info)
  File "C:\Python33\lib\site-packages\django\utils\six.py", line 659, in reraise
    raise value
  File "C:\Python33\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python33\lib\site-packages\django\contrib\auth\decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\python33\assessmenttoolstaging\source\rubricapp\views.py", line 123, in rubric_page
    RubricData.objects.create(assignment=classassignment, enrollment__student=student)
  File "C:\Python33\lib\site-packages\django\db\models\manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Python33\lib\site-packages\django\db\models\query.py", line 346, in create
    obj = self.model(**kwargs)
  File "C:\Python33\lib\site-packages\django\db\models\base.py", line 480, in __init__
    raise TypeError("'%s' is an invalid keyword argument for this function" % list(kwargs)[0])
TypeError: 'enrollment__student' is an invalid keyword argument for this function

======================================================================
ERROR: test_rubric_page_redirects_correct_page (rubricapp.tests.test_views.StudentandRubricViewTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\python33\assessmenttoolstaging\source\rubricapp\tests\test_views.py", line 540, in test_rubric_page_redirects_correct_page
    response = self.client.get("/assessment/201530/EG500001/writingassignment1/21743148/")
  File "C:\Python33\lib\site-packages\django\test\client.py", line 500, in get
    **extra)
  File "C:\Python33\lib\site-packages\django\test\client.py", line 303, in get
    return self.generic('GET', path, secure=secure, **r)
  File "C:\Python33\lib\site-packages\django\test\client.py", line 379, in generic
    return self.request(**r)
  File "C:\Python33\lib\site-packages\django\test\client.py", line 466, in request
    six.reraise(*exc_info)
  File "C:\Python33\lib\site-packages\django\utils\six.py", line 659, in reraise
    raise value
  File "C:\Python33\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python33\lib\site-packages\django\contrib\auth\decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\python33\assessmenttoolstaging\source\rubricapp\views.py", line 123, in rubric_page
    RubricData.objects.create(assignment=classassignment, enrollment__student=student)
  File "C:\Python33\lib\site-packages\django\db\models\manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Python33\lib\site-packages\django\db\models\query.py", line 346, in create
    obj = self.model(**kwargs)
  File "C:\Python33\lib\site-packages\django\db\models\base.py", line 480, in __init__
    raise TypeError("'%s' is an invalid keyword argument for this function" % list(kwargs)[0])
TypeError: 'enrollment__student' is an invalid keyword argument for this function

======================================================================
ERROR: test_rubric_page_shows_rubric_name (rubricapp.tests.test_views.StudentandRubricViewTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\python33\assessmenttoolstaging\source\rubricapp\tests\test_views.py", line 489, in test_rubric_page_shows_rubric_name
    response = self.client.get("/assessment/201530/EG500001/writingassignment1/21743148/")
  File "C:\Python33\lib\site-packages\django\test\client.py", line 500, in get
    **extra)
  File "C:\Python33\lib\site-packages\django\test\client.py", line 303, in get
    return self.generic('GET', path, secure=secure, **r)
  File "C:\Python33\lib\site-packages\django\test\client.py", line 379, in generic
    return self.request(**r)
  File "C:\Python33\lib\site-packages\django\test\client.py", line 466, in request
    six.reraise(*exc_info)
  File "C:\Python33\lib\site-packages\django\utils\six.py", line 659, in reraise
    raise value
  File "C:\Python33\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python33\lib\site-packages\django\contrib\auth\decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\python33\assessmenttoolstaging\source\rubricapp\views.py", line 123, in rubric_page
    RubricData.objects.create(assignment=classassignment, enrollment__student=student)
  File "C:\Python33\lib\site-packages\django\db\models\manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Python33\lib\site-packages\django\db\models\query.py", line 346, in create
    obj = self.model(**kwargs)
  File "C:\Python33\lib\site-packages\django\db\models\base.py", line 480, in __init__
    raise TypeError("'%s' is an invalid keyword argument for this function" % list(kwargs)[0])
TypeError: 'enrollment__student' is an invalid keyword argument for this function

======================================================================
ERROR: test_rubric_shows_a_cell_under_excellent (rubricapp.tests.test_views.StudentandRubricViewTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\python33\assessmenttoolstaging\source\rubricapp\tests\test_views.py", line 484, in test_rubric_shows_a_cell_under_excellent
    response = self.client.get("/assessment/201530/EG500001/writingassignment1/21743148/")
  File "C:\Python33\lib\site-packages\django\test\client.py", line 500, in get
    **extra)
  File "C:\Python33\lib\site-packages\django\test\client.py", line 303, in get
    return self.generic('GET', path, secure=secure, **r)
  File "C:\Python33\lib\site-packages\django\test\client.py", line 379, in generic
    return self.request(**r)
  File "C:\Python33\lib\site-packages\django\test\client.py", line 466, in request
    six.reraise(*exc_info)
  File "C:\Python33\lib\site-packages\django\utils\six.py", line 659, in reraise
    raise value
  File "C:\Python33\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python33\lib\site-packages\django\contrib\auth\decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\python33\assessmenttoolstaging\source\rubricapp\views.py", line 123, in rubric_page
    RubricData.objects.create(assignment=classassignment, enrollment__student=student)
  File "C:\Python33\lib\site-packages\django\db\models\manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Python33\lib\site-packages\django\db\models\query.py", line 346, in create
    obj = self.model(**kwargs)
  File "C:\Python33\lib\site-packages\django\db\models\base.py", line 480, in __init__
    raise TypeError("'%s' is an invalid keyword argument for this function" % list(kwargs)[0])
TypeError: 'enrollment__student' is an invalid keyword argument for this function

======================================================================
ERROR: test_student_and_rubric_view_has_excellent_grade (rubricapp.tests.test_views.StudentandRubricViewTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\python33\assessmenttoolstaging\source\rubricapp\tests\test_views.py", line 479, in test_student_and_rubric_view_has_excellent_grade
    response = self.client.get("/assessment/201530/EG500001/writingassignment1/21743148/")
  File "C:\Python33\lib\site-packages\django\test\client.py", line 500, in get
    **extra)
  File "C:\Python33\lib\site-packages\django\test\client.py", line 303, in get
    return self.generic('GET', path, secure=secure, **r)
  File "C:\Python33\lib\site-packages\django\test\client.py", line 379, in generic
    return self.request(**r)
  File "C:\Python33\lib\site-packages\django\test\client.py", line 466, in request
    six.reraise(*exc_info)
  File "C:\Python33\lib\site-packages\django\utils\six.py", line 659, in reraise
    raise value
  File "C:\Python33\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python33\lib\site-packages\django\contrib\auth\decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\python33\assessmenttoolstaging\source\rubricapp\views.py", line 123, in rubric_page
    RubricData.objects.create(assignment=classassignment, enrollment__student=student)
  File "C:\Python33\lib\site-packages\django\db\models\manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Python33\lib\site-packages\django\db\models\query.py", line 346, in create
    obj = self.model(**kwargs)
  File "C:\Python33\lib\site-packages\django\db\models\base.py", line 480, in __init__
    raise TypeError("'%s' is an invalid keyword argument for this function" % list(kwargs)[0])
TypeError: 'enrollment__student' is an invalid keyword argument for this function

======================================================================
ERROR: test_student_and_rubric_view_returns_correct_template (rubricapp.tests.test_views.StudentandRubricViewTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\python33\assessmenttoolstaging\source\rubricapp\tests\test_views.py", line 469, in test_student_and_rubric_view_returns_correct_template
    response = self.client.get("/assessment/201530/EG500001/writingassignment1/21743148/")
  File "C:\Python33\lib\site-packages\django\test\client.py", line 500, in get
    **extra)
  File "C:\Python33\lib\site-packages\django\test\client.py", line 303, in get
    return self.generic('GET', path, secure=secure, **r)
  File "C:\Python33\lib\site-packages\django\test\client.py", line 379, in generic
    return self.request(**r)
  File "C:\Python33\lib\site-packages\django\test\client.py", line 466, in request
    six.reraise(*exc_info)
  File "C:\Python33\lib\site-packages\django\utils\six.py", line 659, in reraise
    raise value
  File "C:\Python33\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python33\lib\site-packages\django\contrib\auth\decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\python33\assessmenttoolstaging\source\rubricapp\views.py", line 123, in rubric_page
    RubricData.objects.create(assignment=classassignment, enrollment__student=student)
  File "C:\Python33\lib\site-packages\django\db\models\manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Python33\lib\site-packages\django\db\models\query.py", line 346, in create
    obj = self.model(**kwargs)
  File "C:\Python33\lib\site-packages\django\db\models\base.py", line 480, in __init__
    raise TypeError("'%s' is an invalid keyword argument for this function" % list(kwargs)[0])
TypeError: 'enrollment__student' is an invalid keyword argument for this function

======================================================================
ERROR: test_student_and_rubric_view_shows_student_name (rubricapp.tests.test_views.StudentandRubricViewTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\python33\assessmenttoolstaging\source\rubricapp\tests\test_views.py", line 474, in test_student_and_rubric_view_shows_student_name
    response = self.client.get("/assessment/201530/EG500001/writingassignment1/21743148/")
  File "C:\Python33\lib\site-packages\django\test\client.py", line 500, in get
    **extra)
  File "C:\Python33\lib\site-packages\django\test\client.py", line 303, in get
    return self.generic('GET', path, secure=secure, **r)
  File "C:\Python33\lib\site-packages\django\test\client.py", line 379, in generic
    return self.request(**r)
  File "C:\Python33\lib\site-packages\django\test\client.py", line 466, in request
    six.reraise(*exc_info)
  File "C:\Python33\lib\site-packages\django\utils\six.py", line 659, in reraise
    raise value
  File "C:\Python33\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python33\lib\site-packages\django\contrib\auth\decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\python33\assessmenttoolstaging\source\rubricapp\views.py", line 123, in rubric_page
    RubricData.objects.create(assignment=classassignment, enrollment__student=student)
  File "C:\Python33\lib\site-packages\django\db\models\manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Python33\lib\site-packages\django\db\models\query.py", line 346, in create
    obj = self.model(**kwargs)
  File "C:\Python33\lib\site-packages\django\db\models\base.py", line 480, in __init__
    raise TypeError("'%s' is an invalid keyword argument for this function" % list(kwargs)[0])
TypeError: 'enrollment__student' is an invalid keyword argument for this function

======================================================================
FAIL: test_semester_page_can_show_without_redirecting (rubricapp.tests.test_views.ClassViewTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\python33\assessmenttoolstaging\source\rubricapp\tests\test_views.py", line 255, in test_semester_page_can_show_without_redirecting
    self.assertContains(response, 'Bob DaBuilder')
  File "C:\Python33\lib\site-packages\django\test\testcases.py", line 358, in assertContains
    msg_prefix + "Couldn't find %s in response" % text_repr)
AssertionError: False is not true : Couldn't find 'Bob DaBuilder' in response

----------------------------------------------------------------------
Ran 69 tests in 8.458s

FAILED (failures=1, errors=16)
